# permissions for end users to edit pgclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: pgcluster-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: db-operator-poc
    app.kubernetes.io/part-of: db-operator-poc
    app.kubernetes.io/managed-by: kustomize
  name: pgcluster-editor-role
rules:
- apiGroups:
  - apps.pg.dboperator.io
  resources:
  - pgclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.pg.dboperator.io
  resources:
  - pgclusters/status
  verbs:
  - get
