---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - apps.pg.dboperator.io
  resources:
  - pgclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - apps.pg.dboperator.io
  resources:
  - pgclusters/finalizers
  verbs:
  - update
- apiGroups:
  - apps.pg.dboperator.io
  resources:
  - pgclusters/status
  verbs:
  - get
  - patch
  - update
